[params.author]
  name = "Israr Khan"
  image = "img/pp.jpeg"
  headline = "CS Student | Cybersecurity | Systems Programming"
 
  links = [
    { github = "https://github.com/israrkhan-cys" },
    { email = "mailto:7israr.work@gmail.com" },
    { linkden = "www.linkedin.com/in/muhammad-israr-01364a321" },
    { instagram = "https://instagram.com/zephyr_.o2" }
  ]
