[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 20


[[main]]
  name = "CTF writeups"
  pageRef = "CTF writeups"
  weight = 20


[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30
  
[[main]]
  name = "Now"
  pageRef = "now"
  weight = 40  

