colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = false



[homepage]
  layout = "background"
  homepageImage = "img/bg.jpg"
  showRecent = true
  recentLimit = 6
  showMoreLink = true
  showMoreLinkDest = "posts"

[article]
  showDate = true
  showReadingTime = true
  showTableOfContents = true
  showTags = true
  showAuthor = true
  showTaxonomies = true  # 👈 NEW - shows categories/tags at bottom
  #showEdit = false 

[list]
  showSummary = true
  groupByYear = false
   showTableOfContents = false

[footer]
  showCopyright = true
  showThemeAttribution = false
